version: "1.0"

connections:
  staging:
    dump_file: "phase_00/dump-myapp-202506302052.sql"
    host: "localhost"
    port: 3306
    database: "staging_mysql"
    username: "${STAGING_DB_USER}"
    password: "${STAGING_DB_PASSWORD}"
  
  microservices:
    product_service:
      host: "localhost"
      port: 3307
      database: "product_microservice"
      username: "${PRODUCT_DB_USER}"
      password: "${PRODUCT_DB_PASSWORD}"

migrations:
  - migration_id: "products_to_microservice"
    description: "Migrate PRODUCTS table to main_products_table and variation_products_table"

    source:
      tables:
        - name: "PRODUCTS"

    targets:
      - database: "product_service"
        table: "main_products_table"

      - database: "product_service"
        table: "variation_products_table"

    transformation:
      type: "custom"  # direct, custom
      script: "migrations/products_transformation.py"
      function: "transform_products_data"
      parameters:
        variation_patterns:
          - regex: "\\s+(\\d+x\\d+)$"
            variation_type: "dimension"
            description: "Match dimension patterns like '20x20', '40x40'"
          - regex: "\\s+(\\d+(?:kg|g|ml|l|oz|lb))$"
            variation_type: "weight_volume" 
            description: "Match weight/volume patterns like '1kg', '500ml'"
          - regex: "\\s+([A-Z]\\w*)$"
            variation_type: "variant"
            description: "Match capitalized variant names"

    dependencies: []
    
    validation:
      post_migration:
        - check: "custom"
          description: "Validate foreign key relationships and data integrity"
        - check: "row_count"
          description: "Ensure no data loss during transformation"
